name: WordPress PHP, JS, and CSS Lint

on: push

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, xml

      - name: Allow Composer Plugin
        run: |
          composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true

      - name: Install Composer dependencies
        run: |
          composer require --dev squizlabs/php_codesniffer:^3.7
          composer require --dev wp-coding-standards/wpcs:^3.0
          composer require --dev phpcsstandards/phpcsutils:^1.0
          composer require --dev phpcsstandards/phpcsextra:^1.0
          composer install --no-interaction --prefer-dist --verbose

      - name: Fix PHPCS issues
        run: |
          ./vendor/bin/phpcbf --standard=.phpcs.xml --report=full --report-width=120 --colors -v || true

      - name: Run PHPCS
        run: |
          ./vendor/bin/phpcs --standard=.phpcs.xml --report=full --report-width=120 --colors -v || true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install JS/CSS linters
        run: |
          npm install --no-save eslint eslint-config-wordpress @wordpress/eslint-plugin @wordpress/scripts @babel/eslint-parser eslint-plugin-react eslint-plugin-react-hooks

      - name: Run ESLint (JS)
        run: |
          npx eslint 'src/**/*.{js,jsx}' --format stylish --max-warnings 0

      - name: Run stylelint (CSS/SCSS)
        run: |
          echo "Running stylelint with debug info..."
          npx stylelint 'src/**/*.{css,scss}' --formatter verbose --max-warnings 0 